name: Linters
on: [push, pull_request]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - run: yarn install
      - name: ESLint
        run: |
          yarn run eslint src
